# Datasource
spring.datasource.url=jdbc:sqlserver://localhost;databaseName=home_energy_tracker_db;encrypt=true;trustServerCertificate=true;namedPipe=\\\\.\\pipe\\LOCALDB#SH328924\\tsql\\query;integratedSecurity=true;authenticationScheme=NTLM;domain=DESKTOP-7CH11HA
spring.datasource.username=User
spring.datasource.password=12Dhjetor+
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
# spring.datasource.hikari.connection-init-sql=USE [home_energy_tracker_db]

# Flyway
spring.flyway.enabled=true
spring.flyway.schemas=dbo
spring.flyway.default-schema=dbo
spring.flyway.locations=classpath:db/migration

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
#spring.jpa.properties.hibernate.default_catalog=home_energy_tracker_db